# Use the official MongoDB image as the base image
FROM mongo

# Set the working directory to /data/db
WORKDIR /data/db

# Expose port 27017 (the default MongoDB port)
EXPOSE 27017

# Start the MongoDB daemon when the container is run
CMD ["mongod"]