scrape_configs:
  - job_name: 'nginx-prometheus-exporter'
    scrape_interval: 1m
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']

  - job_name: 'mongodb-prometheus-exporter'
    scrape_interval: 1m
    static_configs:
      - targets: ['mongodb-exporter:9216']